//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoTarefaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int IDTarefa { get; set; }
        public string Descricao { get; set; }
        public string NomeSetor { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdPrioridade { get; set; }
    
        public virtual Prioridade Prioridade { get; set; }
        public virtual StatusTarefa StatusTarefa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
